#   _       _________          _______  _______                                              
#  ( (    /|\__   __/|\     /|(  ___  )(  ____ \                                             
#  |  \  ( |   ) (   ( \   / )| (   ) || (    \/                                             
#  |   \ | |   | |    \ (_) / | |   | || (_____                                              
#  | (\ \) |   | |     ) _ (  | |   | |(_____  )                                             
#  | | \   |   | |    / ( ) \ | |   | |      ) |                                             
#  | )  \  |___) (___( /   \ )| (___) |/\____) |                                             
#  |/    )_)\_______/|/     \|(_______)\_______)  

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0395f98e-5d02-4dd2-86d3-206259bea9d7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF9D-C94A";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e3f1d885-ddc5-4ef0-a3db-e7bb869ceac5"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
